### ISSUE TITLE
请问可以更新支持一下XTLS Vision协议吗？

### ISSUE THREAD

**Issue by smdx** [reeceyng/v2ray-agent#1]
大佬你好，请问可以更新支持一下XTLS Vision协议吗？谢谢

**Comment by reeceyng** [comment]
等vision成为正式版以后会考虑，现在你可以考虑手动修改支持一下
先把xray更新为预览版
在你用该脚本生成了普通的xtls配置文件以后，编辑/etc/v2ray-agent/xray/ 02_VLESS_TCP_inbounds.json，更改一下几项:

|  更改前   | 更改后  |
|  ----  | ----  |
| "flow":"xtls-rprx-direct"  | "flow":"xtls-rprx-vision" |
|  "security": "xtls"  |  "security": "tls" |
|  "xtlsSettings" |  "tlsSettings" |

然后重启xray
`sudo systemctl restart xray`

客户端使用最新版v2rayN、v2rayNG
或手动配置[config_client.json](https://raw.githubusercontent.com/XTLS/Xray-examples/main/VLESS-TCP-XTLS-Vision/config_client.json)

**Comment by reeceyng** [comment]
@smdx 你可以试一下开发版，然后告诉我有什么bug
`wget -P /root -N --no-check-certificate "https://raw.githubusercontent.com/reeceyng/v2ray-agent/dev/install.sh" && chmod 700 /root/install.sh && /root/install.sh`

**Comment by reeceyng** [comment]
@smdx 麻烦看下原版是正常的吗，因为这里我好像没动

**Comment by smdx** [comment]
我刚才把vps的系统重新dd一遍了，现在重新安装脚本试试。

**Comment by reeceyng** [comment]
> 我刚才把vps的系统重新dd一遍了，现在重新安装脚本试试。

遇到什么问题都可以问

**Comment by smdx** [comment]
成功安装了，使用没问题

**Comment by smdx** [comment]
> > 我刚才把vps的系统重新dd一遍了，现在重新安装脚本试试。
> 
> 遇到什么问题都可以问

你好，反馈个问题。安装的是xray内核在vasma界面显示v2ray-core[未运行]
然后添加黑名单时提示：
按照上面示例录入域名:cn
 ---> 添加成功
 ---> V2Ray关闭成功
V2Ray启动失败

![Screenshot-2022-12-03_230140](https://user-images.githubusercontent.com/9279217/205447414-670b21c1-7f66-42a5-bba2-6f378d032183.jpg)

**Comment by smdx** [comment]
> 

正常运行的

**Comment by reeceyng** [comment]
> > 
> 
> 正常运行的

试下最新的开发版

**Comment by smdx** [comment]
> 

谢谢，这个版本没问题了。

**Comment by reeceyng** [comment]
> > 
> 
> 谢谢，这个版本没问题了。

那就关闭issue了，测试几天后没问题就发布到稳定版
