### ISSUE TITLE
对于服务器已经安装了nginx的处理，或兼容宝塔面板？

### ISSUE THREAD

**Issue by lovelygfj** [reeceyng/v2ray-agent#10]
请问大佬能不能对脚本的兼容性做一些更新？
比如兼容宝塔面板之类的
目前好像只要是预先安装过nginx的机器，就无法安装脚本了
报错如下：
---> 未检测到当前域名的ip
 ---> 请依次进行下列检查
 --->  1.检查域名是否书写正确
 --->  2.检查域名dns解析是否正确
 --->  3.如解析正确，请等待dns生效，预计三分钟内生效
 --->  4.如报Nginx启动问题，请手动启动nginx查看错误，如自己无法处理请提issues
 --->  5.错误日志:<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
 /html>

 ---> 如以上设置都正确，请重新安装纯净系统后再次尝试
 ---> 检测返回值异常，建议手动卸载nginx后重新执行脚本
 ---> 请检查防火墙规则是否开放443、80

麻烦您给看看
谢谢

**Comment by redstoneleo** [comment]
我也希望安装之后能和已有网站共存，我目前的做法是改"/etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json"里inbound的端口号为非443

**Comment by lovelygfj** [comment]
> 

我测试了各种组合，发现其实如果用centos的话，好像是可以兼容的。
但不知道为啥debian的系统好像不行。
这个需求，之前我记得原作者进行过兼容的优化，但不知道为啥现在不行了

**Comment by lovelygfj** [comment]
通过宝塔官网首页的SSH安装能够解决这个问题
先安装宝塔，自动装LNMP含nigix
然后再装八合一脚本即可。

**Comment by redstoneleo** [comment]
如果不安装宝塔只安装nginx也没有现成的方法共存，我建议你重新开启这个issue提醒日后修复

**Comment by reeceyng** [comment]
> 通过宝塔官网首页的SSH安装能够解决这个问题 先安装宝塔，自动装LNMP含nigix 然后再装八合一脚本即可。

那你之前出错的时候是怎么操作的？

**Comment by lovelygfj** [comment]
> > 通过宝塔官网首页的SSH安装能够解决这个问题 先安装宝塔，自动装LNMP含nigix 然后再装八合一脚本即可。
> 
> 那你之前出错的时候是怎么操作的？

报告大佬，我最开始是用它首页的一键脚本装的，装完之后再去装的LNMP套件啥的，就不行。
但后来发现它首页里还有一个SSH方式的安装器，用那个安装器装完以后，会自动把需要的LNMP部署好，都部署好以后，再装8合1脚本就可以了

**Comment by lovelygfj** [comment]
> > 通过宝塔官网首页的SSH安装能够解决这个问题 先安装宝塔，自动装LNMP含nigix 然后再装八合一脚本即可。
> 
> 那你之前出错的时候是怎么操作的？

报告大佬，我最开始是用它首页的一键脚本装的，装完之后再去装的LNMP套件啥的，就不行。
但后来发现它首页里还有一个SSH方式的安装器，用那个安装器装完以后，会自动把需要的LNMP部署好，都部署好以后，再装8合1脚本就可以了

**Comment by redstoneleo** [comment]
> > 通过宝塔官网首页的SSH安装能够解决这个问题 先安装宝塔，自动装LNMP含nigix 然后再装八合一脚本即可。
> 
> 那你之前出错的时候是怎么操作的？

主要是要解决443端口复用的问题

**Comment by lionheart2133** [comment]
> > > 通过宝塔官网首页的SSH安装能够解决这个问题 先安装宝塔，自动装LNMP含nigix 然后再装八合一脚本即可。
> > 
> > 
> > 那你之前出错的时候是怎么操作的？
> 
> 报告大佬，我最开始是用它首页的一键脚本装的，装完之后再去装的LNMP套件啥的，就不行。 但后来发现它首页里还有一个SSH方式的安装器，用那个安装器装完以后，会自动把需要的LNMP部署好，都部署好以后，再装8合1脚本就可以了

我也在搞共存，但是实在没招了。。。请求补充更详细些的设置！
我在安装时使用443端口+let‘’s的自动申请证书时，可以正常使用，但是这样我的宝塔上的博客（xray所使用的域名跟博客域名不同）就无法访问了；
使用其他端口+txt记录申请证书时，就无法连接，服务器上的access.log一直为空。
结果发现了这个issue~能否请抽空补充以下配置让我参考一下：

1. 域名使用的哪个CDN？我怀疑是CF的https是有特定端口限制的，但我端口使用2083时（CF的允许的其中一个端口，参考https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/）仍然不行；宝塔的后台已经开放443和2083端口；
2. 是否更改过宝塔中博客的设置？能不能消除敏感信息贴一下配置呢？
3.脚本安装时网站的默认端口选的是443吗？是先添加的宝塔中网站再安装的脚本还是反过来呢？
 
万分感谢！

**Comment by redstoneleo** [comment]
目前查到可行的方法我是nigix SNI来搞共存

**Comment by lovelygfj** [comment]
大佬，我reopen了，经过好多天的折腾，发现好像还是不能用。
我的操作是这样的：
在Vultr建立一个debian 11的机器
然后通过BT.cn官网上，在线SSH安装的功能，直接安装宝塔，同时部署LMNP那个环境，版本都用默认。
服务器装好以后，发现可以安装脚本。
但脚本装好以后，用给出的服务器配置放到v2rayN里不工作（连不上），也就是xray本身是没有流量的。
猜测可能是nigix有啥错误吧，麻烦大佬有时间时给看看，能不能改一个兼容宝塔面板的脚本。

**Comment by lionheart2133** [comment]
感谢 @redstoneleo 提醒，白天折腾了一下，目前以下设置可以成功共存了，但是速度很慢（后面优化下就摆了），参考的[这篇](https://qoanty.github.io/2021/05/xray-nginx-sni/)和[这篇](https://orzlee.com/proxy/2021/04/13/nginx-sni-offload-port-multiplexing-uses-xray-vless-xtls.html)博客，我提几个使用宝塔时的关键点：

1. 首先运行`bash -c "$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install -u root`装一下xray，使用root才能够正常读取宝塔申请的证书。
2. 然后装上宝塔，LNMP环境，其中nginx需要去软件商店卸载重新编译安装，带上`--with-http_realip_module`和`--with-stream_ssl_preread_module`两个参数
3. 更改nginx配置，按[这篇](https://orzlee.com/proxy/2021/04/13/nginx-sni-offload-port-multiplexing-uses-xray-vless-xtls.html)的来
4. 添加站点A和B，按前面的博客更改配置，宝塔的话选中sever_name之前的部分替换就行，伪装站可以不启用SSL，但是要申请证书，证书路径填伪装站的证书路径；共存的站点看你心情；xray配置文件看着改吧。
5. 在安全里放行这些用过的端口

**Comment by redstoneleo** [comment]
@lionheart2133 厉害！我是非443端口安装科学上网，SNI这个方法是昨天看nginx配置同一个VPS多占点后看到的方法，还没有实践过，结果你做到了！！！
目前我有个[静态站点](https://cloud.tencent.com/developer/article/1811081)也想要https部署，貌似不能写成upstream了，不知道大家有没有方法搞定？

**Comment by redstoneleo** [comment]
编译没问题，问题是如何配置了以https访问并和现有网站共存

**Comment by xiechangan123** [comment]
瞎折腾，现在gfw只看流量不看端口、伪装、协议，一发威把你整个站点都给灭了。。。搞不懂翻和正经建站搅和在一起干什么
