### ISSUE TITLE
请问一下已经安装mack-a的能直接安装这个脚本吗？催更正式版Vision支持

### ISSUE THREAD

**Issue by Jimmisama** [reeceyng/v2ray-agent#12]
还是需要卸载？

顺便问一下能把vision加到默认的非测试版一键配置里面里面吗。。。这样正式版一键就有vision了。。现在正式版xray 1.7.2了

然后就是名字太不直观了。。像原脚本一样名字是“vless_ws_tls”这种就好了。。

**Comment by reeceyng** [comment]
切换到正式版了
至于vision，因为它和其他的xtls是无法共存的，我暂时把它独立出来了，等其他的xtls彻底淘汰以后再用它代替xtls
