### ISSUE TITLE
CloudFlare CDN

### ISSUE THREAD

**Issue by JForJannet** [reeceyng/v2ray-agent#13]
Hi, when i use cf cdn meaning that when i checked proxied tick in cloudflare the vless vmess or trojan doesn't work at all even those with cdn support doesn't work can you help me how use cloudflare cdn on v2rayAgent? Thanks.

**Comment by KourosZanbouri** [comment]
@JForJannet The cloud analyzed by the A record must be grey [If it is not grey, it will affect the automatic renewal of the certificate for the scheduled task]

The proxy status for A record should be grey (DNS only)

**Comment by JForJannet** [comment]
I know that, i want to check proxied in my A record because of prevent of detecting and blocking my ip via my domain name.
