### ISSUE TITLE
是否可以升级一下v2ray-core的版本

### ISSUE THREAD

**Issue by sdshdv** [reeceyng/v2ray-agent#14]
脚本使用的一直是旧版本的v4.45.2版本，但是最新版已经到v5.x了，是否可以考虑对v2ray-core进行升级，或者加个v4,v5双版本自选安装的选项

**Comment by reeceyng** [comment]
抱歉，由于我一直以来使用的是xray，而且v2ray从v4到v5配置的更新似乎不少，所以暂时不做这个了，就先保持v4的最新版吧
