### ISSUE TITLE
Xray启动失败

### ISSUE THREAD

**Issue by Gslw** [reeceyng/v2ray-agent#19]
Xray启动失败
请手动执行【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】，查看错误日志

root@C20220617175219:~# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.7.2 (Xray, Penetrates Everything.) Custom (go1.19.4 linux/amd64)
A unified platform for anti-censorship.
2023/01/12 02:15:31 Using confdir from arg: /etc/v2ray-agent/xray/conf
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
Failed to start: app/proxyman/inbound: failed to listen TCP on 31299 > transport/internet: failed to listen on address: 127.0.0.1:31299 > transport/internet/websocket: failed to listen TCP(for WS) on 127.0.0.1:31299 > listen tcp 127.0.0.1:31299: bind: cannot assign requested address

**Comment by reeceyng** [comment]
是否31299端口已被占用？

**Comment by Gslw** [comment]
> 是否31299端口已被占用？

Xray启动失败
请手动执行【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】，查看错误日志
root@C20220617175219:~# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.7.2 (Xray, Penetrates Everything.) Custom (go1.19.4 linux/amd64)
A unified platform for anti-censorship.
2023/01/12 12:20:29 Using confdir from arg: /etc/v2ray-agent/xray/conf
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
Failed to start: app/proxyman/inbound: failed to listen TCP on 31299 > transport/internet: failed to listen on address: 127.0.0.1:31299 > transport/internet/websocket: failed to listen TCP(for WS) on 127.0.0.1:31299 > listen tcp 127.0.0.1:31299: bind: cannot assign requested address
root@C20220617175219:~# netstat -tln | grep 31299
root@C20220617175219:~# netstat -anp | grep 31299
root@C20220617175219:~# netstat -anp | grep 31299
root@C20220617175219:~#
netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      543/sshd: /usr/sbin
tcp        0     64 155.94.146.68:22        120.221.105.191:9398    ESTABLISHED 1951/sshd: root@pts
tcp        0      0 155.94.146.68:22        183.107.196.55:36599    TIME_WAIT   -
tcp        0      0 155.94.146.68:22        120.221.105.191:10221   ESTABLISHED 1958/sshd: root@not
tcp6       0      0 :::22                   :::*                    LISTEN      543/sshd: /usr/sbin
udp        0      0 127.0.0.1:323           0.0.0.0:*                           499/chronyd
udp6       0      0 ::1:323                 :::*                                499/chronyd
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ]         DGRAM                    13175    724/systemd          /run/user/0/systemd/notify
unix  2      [ ACC ]     STREAM     LISTENING     13178    724/systemd          /run/user/0/systemd/private
unix  3      [ ]         DGRAM                    1843     1/init               /run/systemd/notify
unix  2      [ ACC ]     STREAM     LISTENING     1846     1/init               /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     13184    724/systemd          /run/user/0/gnupg/S.dirmngr
unix  2      [ ACC ]     STREAM     LISTENING     13186    724/systemd          /run/user/0/gnupg/S.gpg-agent.browser
unix  2      [ ACC ]     STREAM     LISTENING     1848     1/init               /run/systemd/userdb/io.systemd.DynamicUser
unix  2      [ ACC ]     STREAM     LISTENING     13188    724/systemd          /run/user/0/gnupg/S.gpg-agent.extra
unix  2      [ ACC ]     STREAM     LISTENING     1849     1/init               /run/systemd/io.system.ManagedOOM
unix  2      [ ACC ]     STREAM     LISTENING     13190    724/systemd          /run/user/0/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     13192    724/systemd          /run/user/0/gnupg/S.gpg-agent
unix  2      [ ]         DGRAM                    9626     1/init               /run/systemd/journal/syslog
unix  2      [ ACC ]     STREAM     LISTENING     9628     1/init               /run/systemd/fsck.progress
unix  8      [ ]         DGRAM                    9632     1/init               /run/systemd/journal/dev-log
unix  6      [ ]         DGRAM                    9634     1/init               /run/systemd/journal/socket
unix  2      [ ACC ]     STREAM     LISTENING     9636     1/init               /run/systemd/journal/stdout
unix  2      [ ACC ]     SEQPACKET  LISTENING     9638     1/init               /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     1869     218/systemd-journal  /run/systemd/journal/io.systemd.journal
unix  2      [ ACC ]     STREAM     LISTENING     11306    1/init               /run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     11308    1/init               /run/uuidd/request
unix  2      [ ]         DGRAM                    10591    499/chronyd          /run/chrony/chronyd.sock
unix  2      [ ]         DGRAM                    11332    481/cron
unix  3      [ ]         DGRAM                    1844     1/init
unix  3      [ ]         STREAM     CONNECTED     10519    1/init               /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     10565    482/dbus-daemon      /run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     11503    482/dbus-daemon      /run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     10615    487/systemd-logind
unix  3      [ ]         DGRAM                    1845     1/init
unix  2      [ ]         DGRAM                    10584    499/chronyd
unix  3      [ ]         STREAM     CONNECTED     11329    481/cron
unix  3      [ ]         SEQPACKET  CONNECTED     10592    499/chronyd
unix  3      [ ]         STREAM     CONNECTED     10616    482/dbus-daemon      /run/dbus/system_bus_socket
unix  3      [ ]         DGRAM                    9780     238/systemd-udevd
unix  3      [ ]         STREAM     CONNECTED     10628    505/python3
unix  3      [ ]         DGRAM                    9779     238/systemd-udevd
unix  3      [ ]         SEQPACKET  CONNECTED     10593    500/chronyd
unix  3      [ ]         STREAM     CONNECTED     11323    1/init
unix  3      [ ]         STREAM     CONNECTED     13124    1/init               /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     13180    724/systemd
unix  3      [ ]         STREAM     CONNECTED     10767    543/sshd: /usr/sbin
unix  3      [ ]         STREAM     CONNECTED     13122    724/systemd
unix  3      [ ]         DGRAM                    13176    724/systemd
unix  3      [ ]         DGRAM                    13177    724/systemd
unix  3      [ ]         STREAM     CONNECTED     12288    482/dbus-daemon      /run/dbus/system_bus_socket
unix  2      [ ]         DGRAM                    13132    725/(sd-pam)
unix  2      [ ]         DGRAM                    13149    724/systemd
unix  3      [ ]         STREAM     CONNECTED     10768    1/init               /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    9730     1/init
unix  2      [ ]         DGRAM                    10574    485/rsyslogd
unix  3      [ ]         STREAM     CONNECTED     10510    1/init               /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    1871     218/systemd-journal
unix  3      [ ]         STREAM     CONNECTED     10537    487/systemd-logind
unix  2      [ ]         DGRAM                    16863    1951/sshd: root@pts
unix  3      [ ]         STREAM     CONNECTED     9777     1/init               /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     1939     238/systemd-udevd
unix  2      [ ]         DGRAM                    16064    1958/sshd: root@not
unix  3      [ ]         STREAM     CONNECTED     10509    482/dbus-daemon
unix  2      [ ]         DGRAM                    11421    487/systemd-logind
unix  3      [ ]         STREAM     CONNECTED     10563    482/dbus-daemon
unix  3      [ ]         STREAM     CONNECTED     11464    505/python3
unix  3      [ ]         STREAM     CONNECTED     10564    482/dbus-daemon
unix  2      [ ]         STREAM     CONNECTED     16884    1958/sshd: root@not
unix  2      [ ]         STREAM     CONNECTED     16025    1951/sshd: root@pts
unix  2      [ ]         DGRAM                    1948     238/systemd-udevd
unix  3      [ ]         STREAM     CONNECTED     10538    1/init               /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     11465    1/init               /run/systemd/journal/stdout
root@C20220617175219:~#

**Comment by Gslw** [comment]
> 是否31299端口已被占用？

Xray启动失败
请手动执行【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】，查看错误日志
root@C20220617175219:~# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.7.2 (Xray, Penetrates Everything.) Custom (go1.19.4 linux/amd64)
A unified platform for anti-censorship.
2023/01/12 12:20:29 Using confdir from arg: /etc/v2ray-agent/xray/conf
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2023/01/12 12:20:29 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
Failed to start: app/proxyman/inbound: failed to listen TCP on 31299 > transport/internet: failed to listen on address: 127.0.0.1:31299 > transport/internet/websocket: failed to listen TCP(for WS) on 127.0.0.1:31299 > listen tcp 127.0.0.1:31299: bind: cannot assign requested address
root@C20220617175219:~# netstat -tln | grep 31299
root@C20220617175219:~# netstat -anp | grep 31299
root@C20220617175219:~# netstat -anp | grep 31299
root@C20220617175219:~#
netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      543/sshd: /usr/sbin
tcp        0     64 155.94.146.68:22        120.221.105.191:9398    ESTABLISHED 1951/sshd: root@pts
tcp        0      0 155.94.146.68:22        183.107.196.55:36599    TIME_WAIT   -
tcp        0      0 155.94.146.68:22        120.221.105.191:10221   ESTABLISHED 1958/sshd: root@not
tcp6       0      0 :::22                   :::*                    LISTEN      543/sshd: /usr/sbin
udp        0      0 127.0.0.1:323           0.0.0.0:*                           499/chronyd
udp6       0      0 ::1:323                 :::*                                499/chronyd
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ]         DGRAM                    13175    724/systemd          /run/user/0/systemd/notify
unix  2      [ ACC ]     STREAM     LISTENING     13178    724/systemd          /run/user/0/systemd/private
unix  3      [ ]         DGRAM                    1843     1/init               /run/systemd/notify
unix  2      [ ACC ]     STREAM     LISTENING     1846     1/init               /run/systemd/private
unix  2      [ ACC ]     STREAM     LISTENING     13184    724/systemd          /run/user/0/gnupg/S.dirmngr
unix  2      [ ACC ]     STREAM     LISTENING     13186    724/systemd          /run/user/0/gnupg/S.gpg-agent.browser
unix  2      [ ACC ]     STREAM     LISTENING     1848     1/init               /run/systemd/userdb/io.systemd.DynamicUser
unix  2      [ ACC ]     STREAM     LISTENING     13188    724/systemd          /run/user/0/gnupg/S.gpg-agent.extra
unix  2      [ ACC ]     STREAM     LISTENING     1849     1/init               /run/systemd/io.system.ManagedOOM
unix  2      [ ACC ]     STREAM     LISTENING     13190    724/systemd          /run/user/0/gnupg/S.gpg-agent.ssh
unix  2      [ ACC ]     STREAM     LISTENING     13192    724/systemd          /run/user/0/gnupg/S.gpg-agent
unix  2      [ ]         DGRAM                    9626     1/init               /run/systemd/journal/syslog
unix  2      [ ACC ]     STREAM     LISTENING     9628     1/init               /run/systemd/fsck.progress
unix  8      [ ]         DGRAM                    9632     1/init               /run/systemd/journal/dev-log
unix  6      [ ]         DGRAM                    9634     1/init               /run/systemd/journal/socket
unix  2      [ ACC ]     STREAM     LISTENING     9636     1/init               /run/systemd/journal/stdout
unix  2      [ ACC ]     SEQPACKET  LISTENING     9638     1/init               /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     1869     218/systemd-journal  /run/systemd/journal/io.systemd.journal
unix  2      [ ACC ]     STREAM     LISTENING     11306    1/init               /run/dbus/system_bus_socket
unix  2      [ ACC ]     STREAM     LISTENING     11308    1/init               /run/uuidd/request
unix  2      [ ]         DGRAM                    10591    499/chronyd          /run/chrony/chronyd.sock
unix  2      [ ]         DGRAM                    11332    481/cron
unix  3      [ ]         DGRAM                    1844     1/init
unix  3      [ ]         STREAM     CONNECTED     10519    1/init               /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     10565    482/dbus-daemon      /run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     11503    482/dbus-daemon      /run/dbus/system_bus_socket
unix  3      [ ]         STREAM     CONNECTED     10615    487/systemd-logind
unix  3      [ ]         DGRAM                    1845     1/init
unix  2      [ ]         DGRAM                    10584    499/chronyd
unix  3      [ ]         STREAM     CONNECTED     11329    481/cron
unix  3      [ ]         SEQPACKET  CONNECTED     10592    499/chronyd
unix  3      [ ]         STREAM     CONNECTED     10616    482/dbus-daemon      /run/dbus/system_bus_socket
unix  3      [ ]         DGRAM                    9780     238/systemd-udevd
unix  3      [ ]         STREAM     CONNECTED     10628    505/python3
unix  3      [ ]         DGRAM                    9779     238/systemd-udevd
unix  3      [ ]         SEQPACKET  CONNECTED     10593    500/chronyd
unix  3      [ ]         STREAM     CONNECTED     11323    1/init
unix  3      [ ]         STREAM     CONNECTED     13124    1/init               /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     13180    724/systemd
unix  3      [ ]         STREAM     CONNECTED     10767    543/sshd: /usr/sbin
unix  3      [ ]         STREAM     CONNECTED     13122    724/systemd
unix  3      [ ]         DGRAM                    13176    724/systemd
unix  3      [ ]         DGRAM                    13177    724/systemd
unix  3      [ ]         STREAM     CONNECTED     12288    482/dbus-daemon      /run/dbus/system_bus_socket
unix  2      [ ]         DGRAM                    13132    725/(sd-pam)
unix  2      [ ]         DGRAM                    13149    724/systemd
unix  3      [ ]         STREAM     CONNECTED     10768    1/init               /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    9730     1/init
unix  2      [ ]         DGRAM                    10574    485/rsyslogd
unix  3      [ ]         STREAM     CONNECTED     10510    1/init               /run/systemd/journal/stdout
unix  2      [ ]         DGRAM                    1871     218/systemd-journal
unix  3      [ ]         STREAM     CONNECTED     10537    487/systemd-logind
unix  2      [ ]         DGRAM                    16863    1951/sshd: root@pts
unix  3      [ ]         STREAM     CONNECTED     9777     1/init               /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     1939     238/systemd-udevd
unix  2      [ ]         DGRAM                    16064    1958/sshd: root@not
unix  3      [ ]         STREAM     CONNECTED     10509    482/dbus-daemon
unix  2      [ ]         DGRAM                    11421    487/systemd-logind
unix  3      [ ]         STREAM     CONNECTED     10563    482/dbus-daemon
unix  3      [ ]         STREAM     CONNECTED     11464    505/python3
unix  3      [ ]         STREAM     CONNECTED     10564    482/dbus-daemon
unix  2      [ ]         STREAM     CONNECTED     16884    1958/sshd: root@not
unix  2      [ ]         STREAM     CONNECTED     16025    1951/sshd: root@pts
unix  2      [ ]         DGRAM                    1948     238/systemd-udevd
unix  3      [ ]         STREAM     CONNECTED     10538    1/init               /run/systemd/journal/stdout
unix  3      [ ]         STREAM     CONNECTED     11465    1/init               /run/systemd/journal/stdout
root@C20220617175219:~#

**Comment by Gslw** [comment]
Xray启动失败
请手动执行【/etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf】，查看错误日志
root@C20220617175219:~# /etc/v2ray-agent/xray/xray -confdir /etc/v2ray-agent/xray/conf
Xray 1.7.2 (Xray, Penetrates Everything.) Custom (go1.19.4 linux/amd64)
A unified platform for anti-censorship.
2023/01/12 12:27:05 Using confdir from arg: /etc/v2ray-agent/xray/conf
2023/01/12 12:27:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/00_log.json
2023/01/12 12:27:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/02_VLESS_TCP_inbounds.json
2023/01/12 12:27:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/03_VLESS_WS_inbounds.json ] appended inbound with tag:  VLESSWS
2023/01/12 12:27:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_TCP_inbounds.json ] appended inbound with tag:  trojanTCP
2023/01/12 12:27:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/04_trojan_gRPC_inbounds.json ] appended inbound with tag:  trojangRPCTCP
2023/01/12 12:27:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/05_VMess_WS_inbounds.json ] appended inbound with tag:  VMessWS
2023/01/12 12:27:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json
xctl> [ /etc/v2ray-agent/xray/conf/06_VLESS_gRPC_inbounds.json ] appended inbound with tag:  VLESSGRPC
2023/01/12 12:27:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/10_ipv4_outbounds.json
2023/01/12 12:27:05 [Info] infra/conf/serial: Reading config: /etc/v2ray-agent/xray/conf/11_dns.json
Failed to start: app/proxyman/inbound: failed to listen TCP on 31299 > transport/internet: failed to listen on address: 127.0.0.1:31299 > transport/internet/websocket: failed to listen TCP(for WS) on 127.0.0.1:31299 > listen tcp 127.0.0.1:31299: bind: cannot assign requested address
root@C20220617175219:~# netstat -tln | grep 31299
root@C20220617175219:~# netstat -anp | grep 31299
root@C20220617175219:~# lsof -i:31299
root@C20220617175219:~#

并不是太懂，重新安装按照网上的端口占用查询法都没反应。

**Comment by eggydutch** [comment]
似乎是trojan xtls-vision的支持问题：
infra/conf: Trojan clients: "flow" doesn't support "xtls-rprx-vision" in this version

**Comment by reeceyng** [comment]
> 似乎是trojan xtls-vision的支持问题： infra/conf: Trojan clients: "flow" doesn't support "xtls-rprx-vision" in this version

看起来是的，用trojan只能使用direct和splice两种，而且作者似乎也不打算支持trojan
