### ISSUE TITLE
多端口账户协议漏洞

### ISSUE THREAD

**Issue by blueveryday** [reeceyng/v2ray-agent#21]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 多端口账户有协议漏洞。
- 服务器已完全安装xray，启用vless+tcp，vless+ws+CDN，trojan等协议账号使用。
- 443为主端口，添加其他副端口，比如1234,7890等等，任意端口。
- vps的IP没有走CF的CDN转发，所有域名连接都是直连。
- 客户端采用CDN账号连接，走443主端口，连接失败。（情理之中，vps并没有走CDN转发，当然不能使用）。但是相同账号，协议走CDN账号的其他副端口，比如1234,7890，可以正常使用。

**2.安装失败的错误内容或者截图**
- 非安装问题。

**3.系统版本**
- ubuntu 20

**4.脚本版本**
- 2.7.3

**5.核心类型及版本**
- n/a

**Comment by reeceyng** [comment]
没用明白你的意思，最好举个例子

**Comment by blueveryday** [comment]
> 没用明白你的意思，最好举个例子
比如：
安装完成以后，会有两个账号：
1、格式化明文(VLESS+TCP+TLS/xtls-rprx-splice)
    协议类型:VLESS，地址:123.yy.xx，端口:443，用户ID:abcd，安全:tls，传输方式:tcp，flow:xtls-rprx-vision，伪装域名/SNI:123.yy.xx，账户名:12345

2、格式化明文(VLESS+WS+TLS+CDN)
    协议类型:VLESS，地址:123.yy.xx，伪装域名/SNI:123.yy.xx，端口:443，用户ID:abcd，安全:tls，传输方式:ws，路径:/ezzgws，账户名:12345

然后添加一个副端口，443（默认为主端口），得到另外两个不同端口的账号：
3、格式化明文(VLESS+TCP+TLS/xtls-rprx-splice)
    协议类型:VLESS，地址:123.yy.xx，端口:1443，用户ID:abcd，安全:tls，传输方式:tcp，flow:xtls-rprx-vision，伪装域名/SNI:123.yy.xx，账户名:12345

4、格式化明文(VLESS+WS+TLS+CDN)
    协议类型:VLESS，地址:123.yy.xx，伪装域名/SNI:123.yy.xx，端口:1443，用户ID:abcd，安全:tls，传输方式:ws，路径:/ezzgws，账户名:12345

众所周知，走CDN的服务和不走CDN的服务，是互锁的，不能同时使用。因为CF里面代不代理服务器的流量是二选一的。（小云朵是否打开不打开自己决定）

问题场景：
服务器不走CDN中转流量的情况下，我们只能正常使用账号1、3的443端口和1443端口的服务。
照理说账号2、4是用不起的，玩过的人都知道。
问题是，未开启CDN中转流量服务的前提下，4账号居然可以正常使用，这是不应该的。
这就是我要反馈的问题。

**Comment by reeceyng** [comment]
@blueveryday
VLESS+WS+TLS+CDN 的意思是“可以”搭配CDN使用，而不是“必须”搭配CDN使用，所以你不把云朵点亮的情况下2也应该是可以使用的
**然而**你现在使用不了，原因是xtls使用了vision，目前vision还不支持回落，所以同端口的其他协议都使用不了，所以这算是新xtls协议的不完善，但不是安全bug

**Comment by reeceyng** [comment]
@blueveryday
VLESS+WS+TLS+CDN 的意思是“可以”搭配CDN使用，而不是“必须”搭配CDN使用，所以你不把云朵点亮的情况下1、2、3、4都应该是可以使用的
然而你现在443端口的使用不了，其实是有问题的

**Comment by blueveryday** [comment]
> @blueveryday VLESS+WS+TLS+CDN 的意思是“可以”搭配CDN使用，而不是“必须”搭配CDN使用，所以你不把云朵点亮的情况下1、2、3、4都应该是可以使用的 然而你现在443端口的使用不了，其实是有问题的

443有时候会被封端口。
我本来理解的是ws+cdn的话，cf不开流量中转的话，是不能使用的。

**Comment by reeceyng** [comment]
> cf不开流量中转的话，是不能使用的。

想实现的话需要用iptables屏蔽掉非cloudflare的ip
