### ISSUE TITLE
problem for instal

### ISSUE THREAD

**Issue by hossinizadeh** [reeceyng/v2ray-agent#22]
hi would you please help me becuase after install at finish i see this error.

Progress 12/13 : Verify service startup status
 ---> Service started successfully
/root/install.sh: line 447: jq: command not found
/root/install.sh: line 450: jq: command not found
/root/install.sh: line 452: jq: command not found
/root/install.sh: line 454: jq: command not found
/root/install.sh: line 456: jq: command not found
/root/install.sh: line 462: jq: command not found
/root/install.sh: line 479: jq: command not found
/root/install.sh: line 484: jq: command not found
/root/install.sh: line 485: jq: command not found
/root/install.sh: line 486: jq: command not found
/root/install.sh: line 490: jq: command not found

Progress 13/13 : Account
===================== VLESS TCP TLS/XTLS-direct/XTLS-splice ======================

/root/install.sh: line 3296: jq: command not found
/root/install.sh: line 3296: jq: command not found

================================ VLESS WS TLS CDN ================================

/root/install.sh: line 3310: jq: command not found
/root/install.sh: line 3310: jq: command not found

================================ VMess WS TLS CDN ================================

/root/install.sh: line 3332: jq: command not found
/root/install.sh: line 3332: jq: command not found

=============================== VLESS gRPC TLS CDN ===============================

 ---> gRPC is in the testing stage and may not be compatible with the client you are using.If it cannot be used, please ignore it
/root/install.sh: line 3348: jq: command not found
/root/install.sh: line 3348: jq: command not found

==================================  Trojan TLS  ==================================

/root/install.sh: line 3363: jq: command not found
/root/install.sh: line 3363: jq: command not found

==============================

**Comment by reeceyng** [comment]
- apt-get update 
- apt-get -y install jq
