### ISSUE TITLE
incorrect flow when using VISION

### ISSUE THREAD

**Issue by free-the-internet** [reeceyng/v2ray-agent#24]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
When using "3.Xray-core(使用xtls-rprx-vision)", it add a user with flow "xtls-rprx-vision" during installation process.
After, when using option number 5 to add a new user, it adds the user but the flow is "xtls-rprx-direct" in the config file "02_VLESS_TCP_inbounds.json"

**2.安装失败的错误内容或者截图**
- empty

**3.系统版本**
- Debian 10

**4.脚本版本**
v 2.7.3

**5.核心类型及版本**
xray 1.7.2

**Comment by reeceyng** [comment]
fixed in 4c83d01ce60cb1f0576fe13dd12324d9cdf12846, update and try

**Comment by free-the-internet** [comment]
Now, it adds flows to all configs files. In fact we need flow just in VLESS config file beginning with `02`.
Also, I see that it generates WS+CDN client configs with address: `www.cloudflare.com` which is wrong in my opinion. We can't use it in Iran. Maybe it is special for China somehow?
