### ISSUE TITLE
net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by darkkeade** [reeceyng/v2ray-agent#25]
> 请仔细填写每一项，并回复自己详细的错误信息

**1.问题描述**
- 安装完成当天使用正常，路由器端和手机断使用都没有问题，第二天出现net/http: TLS handshake timeout故障

**2.安装失败的错误内容或者截图**
- 手机端使用V2RayNG连接后测试报net/http: TLS handshake timeout

**3.系统版本**
- debian10 64位

**4.脚本版本**
- v2.7.3 VLESS+TCP+TLS使用域名伪装

**5.核心类型及版本**
- Xray-core

**Comment by reeceyng** [comment]
看起来是端口被封了，在ping.pe测试一下端口是否正常

**Comment by darkkeade** [comment]
是搬瓦工的端口问题，已经改端口解决了，谢谢
