### ISSUE TITLE
alpn不能切换，提示为null

### ISSUE THREAD

**Issue by gxhunter1982** [reeceyng/v2ray-agent#3]
选择14.切换alpn，提示：
当前alpn首位为:null

输入啥都提示选择错误

2.7.0版出现过一次，选择“1重新安装”后修复。

现在2.7.1版在另一台机器上也出现这问题，没法切换，不管是选“1重新安装”，还是卸载脚本后重装也是如此。

![alpn](https://user-images.githubusercontent.com/78349261/205886141-cf034f16-f3f0-452d-917a-6170d5857892.png)

**Comment by gxhunter1982** [comment]
> 试一下最新版

已经是最新的2.7.1版了。2.7.1版卸载后重装也是如此

**Comment by reeceyng** [comment]
> 

刚更新了2.7.2

**Comment by gxhunter1982** [comment]
啊，刚才回复前，看过发布页是没有更新的，现在刷新出来了。
已经OK了

**Comment by gxhunter1982** [comment]
已修复
