### ISSUE TITLE
IPv6 only VPS 安装问题

### ISSUE THREAD

**Issue by socosfly** [reeceyng/v2ray-agent#8]
我有一台纯IPv6的机器，脚本可以安装，申请证书也都没有问题，但是无法访问。
请问要修改哪些配置才能让xray监听v6的端口呢？

**Comment by reeceyng** [comment]
我没有纯ipv6的服务器，没办法进行调试
不过我认为不是入站的问题，而是出站的问题
我重新安装下最新的开发版试试，然后告诉我能否使用

**Comment by mfat** [comment]
I used this script successfully on an ipv6 server. Just add an AAAA record in Cloudflare and make sure it's gray (DNS only).  After the script ran successfully and you get the configs, make it orange ( PROXY ON)
